# devops-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: devops
  labels:
    app: devops-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-runner
  template:
    metadata:
      labels:
        app: devops-runner
    spec:
      containers:
      - name: devops-runner
        image: devopsacr14044.azurecr.io/devops-runner:v1.0.0 # Add your ACR respository
        command:
        - sleep
        args:
        - 99d
        volumeMounts:
          - mountPath: "/home/devops"
            name: runner-data
      volumes:
        - name: runner-data
          persistentVolumeClaim:
            claimName: devops-pvc