name: $(Date:yyyyMMdd)$(Rev:.r)

pool: DevOpsOnAks

trigger:
  batch: true

stages:
  - stage: buildImage
    displayName: Build Application Image
    jobs:
      - job: build
        steps:
          - checkout: self
            clean: true

          - script: |
              sleep 10000

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'DevopsAKS'
              scriptType: 'pscore'
              scriptLocation: inlineScript
              inlineScript: |
                az acr build -f /devops-runner/_work/devops-runner/devops-runner/Dockerfile -t devopsacr14044.azurecr.io/devops-demo:$(Build.SourceVersion) -r devopsacr14044 .