name: $(Date:yyyyMMdd)$(Rev:.r)

pool: DevOpsOnAks

trigger:
  batch: true

stages:
  - stage: buildImage
    displayName: Build Application Image
    jobs:
      - job: build
        steps:
          - checkout: self
            clean: true

          - task: AzureCLI@2
            displayName: Build image
            inputs:
              azureSubscription: 'DevopsAKS'
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                az acr build -f $(Agent.BuildDirectory)/s/Dockerfile -t devopsacr14044.azurecr.io/devops-demo:$(Build.SourceVersion) -r devopsacr14044 .

          - script: |
              sed 's|IMAGE|devopsacr14044.azurecr.io/devops-demo|g; s/TAG/$(Build.SourceVersion)/g' $(Agent.BuildDirectory)/s/app.yaml > $(Agent.BuildDirectory)/s/deploy-app.yaml
            displayName: Update manifest

          - task: Kubernetes@1
            displayName: Deploy application
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: 'DevopsAKS'
              azureResourceGroup: 'devops-runner-rg'
              kubernetesCluster: 'aks-devops-runner'
              command: apply
              arguments: -f $(Agent.BuildDirectory)/s/deploy-app.yaml