name: $(Date:yyyyMMdd)$(Rev:.r)

pool: coolpool

trigger:
  batch: true

stages:
  - stage: buildPushDeploy
    displayName: Build, Push and Deploy
    jobs:
      - job: build
        steps:
          - checkout: self
            clean: true

          - script: |
              set -euo pipefail
              az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE)
              az acr build -f $(Agent.BuildDirectory)/s/Dockerfile -t ConRepo.azurecr.io/devops-demo:$(Build.SourceVersion) -r devopsacr32044 .
            displayName: Log in and push image to ACR

          - script: |
              set -euo pipefail
              az aks get-credentials --resource-group automation-rg --name orkideaks --overwrite-existing
              kubelogin convert-kubeconfig -l workloadidentity
              sed 's|IMAGE|ConRepo.azurecr.io/devops-demo|g; s/TAG/$(Build.SourceVersion)/g' $(Agent.BuildDirectory)/s/app.yaml | kubectl apply -f -
            displayName: Get AKS credentials and deploy app
